Авторизация пользователя и сохранение jwt
Andy-Esm/chill_todo pull request #15
Opened 2024-01-24 15:23 UTC by MSDipper

Добавил сохранение токена в cookies, при отправке запроса.

2024-01-24 15:29 UTC, Sorrint commented on src/features/LoginForm/ui/LoginForm.tsx
> +    // alert('Отправка данных формы входа')
можно удалить alert сразу

2024-01-24 15:48 UTC, Sorrint requested changes

2024-01-24 15:48 UTC, Sorrint commented on src/features/RegistrationForm/ui/RegistrationForm.tsx
> +    console.log(result)
алерт и консоль  тоже удалить

2024-01-24 15:48 UTC, Sorrint commented on src/shared/lib/middlewares/delayRTKMiddleware/delayRTKMiddleware.ts
> +  }
токен все-таки нужно отправлять с заголовками. 
Не знаю, сработает ли здесь селектор для store. Можно решить таким способом:
```
const parsingCookie = (name: string) => {
  const cookies = document.cookie
  const arrCookies = cookies.split('; ')
  const authCookie = arrCookies.find((el) => el.includes(name))
  if (authCookie) {
    return authCookie.split('=')[1]
  } else {
    return ''
  }
}
const token = parsingCookie('token')

const baseQuery = fetchBaseQuery({
  baseUrl: `${url}`,
  prepareHeaders: (headers) => {
    headers.set('authorization', `Bearer ${token ?? ''}`)
    return headers
  },
})

export const baseQueryWithDelay: BaseQueryFn<
  string | FetchArgs,
  unknown,
  FetchBaseQueryError,
  ExtraOptionsWithDelay
> = async (args, api, extraOptions) => {
  return new Promise((resolve) => {
    setTimeout(async () => resolve(await baseQuery(args, api, extraOptions)), 0)
  })
}
```

2024-01-24 15:48 UTC, Sorrint commented on src/shared/lib/store/tokenSlice.ts
> +    },
может вообще удалять поле token?

2024-01-24 15:48 UTC, Sorrint commented on src/shared/lib/store/tokenSlice.ts
> +      document.cookie = `token=${action.payload}; expires=${expires.toUTCString()};`
7 дней? лучше час) можно пока не трогать, пока refresh токена нет

2024-01-24 18:05 UTC, Andy-Esm approved these changes

2024-01-25 16:29 UTC, Sorrint approved these changes

2024-01-25 16:29 UTC, merged