Поправил курсор на дефолтное
Andy-Esm/chill_todo pull request #3
Opened 2024-01-18 12:32 UTC by bemal63

2024-01-18 14:45 UTC, Sorrint commented
Попробуй заменить все, что на скринах, на компонент header, чтобы для них выставить курсор pointer
![photo_2024-01-18_22-45-35](https://github.com/Andy-Esm/chill_todo/assets/96907952/97208021-8e68-472b-b3a9-22fc9c75faf1)
![photo_2024-01-18_22-45-31](https://github.com/Andy-Esm/chill_todo/assets/96907952/b2088a57-87d5-4bca-bee2-bbe33f1385d1)
![photo_2024-01-18_22-45-27](https://github.com/Andy-Esm/chill_todo/assets/96907952/c629b3bf-d306-43df-9be0-685d4192e933)
![photo_2024-01-18_22-33-07](https://github.com/Andy-Esm/chill_todo/assets/96907952/b9bab66a-3d8d-43d8-8f24-82f1ee89a2f0)

2024-01-18 14:48 UTC, Sorrint requested changes
Написал в комментарии

2024-01-18 15:20 UTC, Andy-Esm requested changes
Антон написал что поправить)

2024-01-22 16:29 UTC, Andy-Esm submitted a review, later dismissed
Вроде все норм, но было бы хорошо, если бы ты добил и сделал так что бы стили заголовков на всех страницах были одинаковые. Я имею в виду так как на странице задачи написан "Список задач" Но я забью это новой задачей в списке, что бы ты с этой не зависал

2024-01-22 17:23 UTC, Sorrint approved these changes

2024-01-22 17:36 UTC, merged